---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: foundryvtt
  namespace: foundryvtt
spec:
  interval: 10m
  chart:
    spec:
      interval: 10m
      chartRef:
        kind: OCIRepository
        name: foundryvtt-helm
        namespace: foundryvtt
  values:
    config:
      domain: tabletop.tres-sims.com

    extraEnvFrom:
      - secretRef:
          name: foundryvtt-creds

    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - host:
            - tabletop.tres-sims.com
          secretName: foundry.tls
