---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: foundryvtt-helm
  namespace: foundryvtt
spec:
  interval: 1m0s
  url: oci://ghcr.io/tressims/charts/foundryvtt
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "14.365.0"
