---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: tetragon
spec:
  interval: 10m
  chart:
    spec:
      chart: tetragon
      version: "1.6.1"
      sourceRef:
        kind: HelmRepository
        name: tetragon-helm
        namespace: tetragon
      interval: 10m
  values:
    tetragon:
      prometheus:
        serviceMonitor:
          enabled: true
      prometheusOperator:
        serviceMonitor:
          enabled: true
