---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: node-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: node-exporter-helm
  interval: 10m
  values:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9100"
    service:
      annotations:
        prometheus.io/scrape: "false"
