---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: flux-operator
    namespace: flux-system
  values:
    server:
      podSecurityContext:
        fsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
