---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: "39.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik-helm
        namespace: traefik
      interval: 10m
  values:
    providers:
      kubernetesIngress:
        enabled: true
    logs:
      general:
        level: DEBUG
    deployment:
      kind: DaemonSet
    service:
      type: NodePort
    hostNetwork: true
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
    ports:
      metrics:
        port: 9200
      websecure:
        port: 443
      web:
        port: 80
