---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-auth
  namespace: o11y
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: infisical
  target:
    name: grafana-auth
    template:
      type: Opaque
      data:
        prometheus_endpoint: "{{.prometheus_endpoint}}"
        prometheus_token: "{{.prometheus_token}}"
        prometheus_user: "{{.prometheus_user}}"
        loki_endpoint: "{{.loki_endpoint}}"
        loki_token: "{{.loki_token}}"
        loki_user: "{{.loki_user}}"
  data:
    - secretKey: prometheus_endpoint
      remoteRef:
        key: /o11y/prometheus_endpoint
    - secretKey: prometheus_token
      remoteRef:
        key: /o11y/prometheus_token
    - secretKey: prometheus_user
      remoteRef:
        key: /o11y/prometheus_user
    - secretKey: loki_endpoint
      remoteRef:
        key: /o11y/loki_endpoint
    - secretKey: loki_token
      remoteRef:
        key: /o11y/loki_token
    - secretKey: loki_user
      remoteRef:
        key: /o11y/loki_user
