---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-helm
  namespace: cert-manager
spec:
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  interval: 10m0s
  url: oci://quay.io/jetstack/charts/cert-manager
  ref:
    semver: "v1.21.0"
